// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlclGqcOOJPOvnus2APS0B-c07QFjVKk4',
    appId: '1:682011230635:web:bcd6bf3427912391ae92ee',
    messagingSenderId: '682011230635',
    projectId: 'mood-tracker-app-8d343',
    authDomain: 'mood-tracker-app-8d343.firebaseapp.com',
    storageBucket: 'mood-tracker-app-8d343.firebasestorage.app',
    measurementId: 'G-EN1CD4QNG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7f-JKYldfkpHIlfzuxppPdNX_wudr8mI',
    appId: '1:682011230635:android:49a174740e21b923ae92ee',
    messagingSenderId: '682011230635',
    projectId: 'mood-tracker-app-8d343',
    storageBucket: 'mood-tracker-app-8d343.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvXsJ3UZKCCN73gOh_y4P__V20Yb9kw8k',
    appId: '1:682011230635:ios:e81b2739a77ec149ae92ee',
    messagingSenderId: '682011230635',
    projectId: 'mood-tracker-app-8d343',
    storageBucket: 'mood-tracker-app-8d343.firebasestorage.app',
    iosBundleId: 'com.example.moodTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvXsJ3UZKCCN73gOh_y4P__V20Yb9kw8k',
    appId: '1:682011230635:ios:e81b2739a77ec149ae92ee',
    messagingSenderId: '682011230635',
    projectId: 'mood-tracker-app-8d343',
    storageBucket: 'mood-tracker-app-8d343.firebasestorage.app',
    iosBundleId: 'com.example.moodTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlclGqcOOJPOvnus2APS0B-c07QFjVKk4',
    appId: '1:682011230635:web:ac1d01f9c805c6bfae92ee',
    messagingSenderId: '682011230635',
    projectId: 'mood-tracker-app-8d343',
    authDomain: 'mood-tracker-app-8d343.firebaseapp.com',
    storageBucket: 'mood-tracker-app-8d343.firebasestorage.app',
    measurementId: 'G-9DSZDB60M3',
  );
}
